FROM python:3.10
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir streamlit requests opencv-python-headless
CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
